try

diff --git a/blobfuse2-release-test.yaml b/blobfuse2-release-test.yaml
--- a/blobfuse2-release-test.yaml
+++ b/blobfuse2-release-test.yaml
@@ -156,38 +156,38 @@ extends:
           env:
             AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
 
-        - job: CheckPipelineStatus
-          displayName: 'Check Triggered Pipeline Status'
-          steps:
-          - script: |
-              echo "Checking the status of the triggered pipeline..."
-              while true; do
-                status=$(az pipelines runs show --organization https://dev.azure.com/$(organization) --project $(project) --pipeline-id $(pipelineId) --run-id $(run_id) --query status --output tsv --only-show-errors)
-                echo "Current status: $status"
-                if [[ "$status" == "completed" || "$status" == "canceled" || "$status" == "failed" ]]; then
-                  echo "Pipeline run $run_id has $status."
-                  break
-                fi
-                echo "Pipeline run $runId is still in progress. Checking again in 30 seconds..."
-                sleep 30
-              done
-            displayName: 'Check Pipeline Status'
-            env:
-              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
-
-        - job: ContinueOriginalPipeline
-          displayName: 'Continue Original Pipeline'
-          dependsOn: CheckPipelineStatus
-          condition: succeeded()
-          steps:
-          - script: 
-              if( "$status" == "completed" ); then
-                echo "Pipeline run $run_id completed successfully. Continuing the original pipeline."
-              else
-                echo "Pipeline run $run_id failed or was canceled. Stopping the original pipeline."
-                exit 1
+      - job: CheckPipelineStatus
+        displayName: 'Check Triggered Pipeline Status'
+        steps:
+        - script: |
+            echo "Checking the status of the triggered pipeline..."
+            while true; do
+              status=$(az pipelines runs show --organization https://dev.azure.com/$(organization) --project $(project) --pipeline-id $(pipelineId) --run-id $(run_id) --query status --output tsv --only-show-errors)
+              echo "Current status: $status"
+              if [[ "$status" == "completed" || "$status" == "canceled" || "$status" == "failed" ]]; then
+                echo "Pipeline run $run_id has $status."
+                break
               fi
-            displayName: 'Continue Pipeline'
+              echo "Pipeline run $runId is still in progress. Checking again in 30 seconds..."
+              sleep 30
+            done
+          displayName: 'Check Pipeline Status'
+          env:
+            AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
+
+      - job: ContinueOriginalPipeline
+        displayName: 'Continue Original Pipeline'
+        dependsOn: CheckPipelineStatus
+        condition: succeeded()
+        steps:
+        - script: 
+            if( "$status" == "completed" ); then
+              echo "Pipeline run $run_id completed successfully. Continuing the original pipeline."
+            else
+              echo "Pipeline run $run_id failed or was canceled. Stopping the original pipeline."
+              exit 1
+            fi
+          displayName: 'Continue Pipeline'
 
         # - script: |
         #     PIPELINE_ID=95  
